package main

var router_template = `
// Code generated by koala tools. DO NOT EDIT.
package router
import(
	"context"
	{{if not .Prefix}}
	"generate/{{.Package.Name}}"
	{{else}}
	{{.Package.Name}} "{{.Prefix}}/generate"
	{{end}}

	{{if not .Prefix}}
	"controller"
	{{else}}
	"{{.Prefix}}/controller"
	{{end}}
	
	"Microservices_demo/tools/middleware"

)
	
type RouterServer struct{}
{{range .Rpc}}


func (s *RouterServer) {{.Name}}(ctx context.Context, r* {{$.Package.Name}}.{{.RequestType}})(resp* {{$.Package.Name}}.{{.ReturnsType}}, err error){
	mvFunc := middleware.BuildServerMiddleware(mv{{.Name}})
	mvResp, err := mvFunc(ctx, r)

	resp = mvResp.(*{{$.Package.Name}}.{{.ReturnsType}})
	return
}

func mv{{.Name}}(ctx context.Context, request interface{})(resp interface{}, err error) {
	r := request.(*{{$.Package.Name}}.{{.RequestType}})
	ctrl := &controller.{{.Name}}Controller{}
	resp ,err = ctrl.CheckParams(ctx, r)
	if err != nil {
		return
	}

	resp, err = ctrl.Run(ctx, r)
	return
}

{{end}}
`
