package main

var router_template = `
// Code generated by koala tools. DO NOT EDIT.
package router
import(
	"context"
	{{if not .Prefix}}
	"{{.Package.Name}}"
	{{else}}
	"{{.Prefix}}/{{.Package.Name}}"
	{{end}}
)
	
type RouterServer struct{}
{{range .Rpc}}
func (s *RouterServer) {{.Name}}(ctx context.Context, r*{{$.Package.Name}}.{{.RequestType}})(resp*{{$.Package.Name}}.{{.ReturnsType}}, err error){
	return
}

{{end}}
`
